#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR="$DIR/"
echo $DIR
source $DIR/../bash/bash_alias.sh
source $DIR/../bash/bash_terminal.sh
source $DIR/../bash/bash_env.sh

# # git branch autocompletion
# if [ -f ~/dotfiles/.git-completion.bash ]; then
#   . ~/dotfiles/.git-completion.bash
# fi

# disable the ctrl-s
stty -ixon

