---
- name: Converge
  hosts: all
  tasks:
    - name: Run nodejs install tasks
      include_tasks: ../../tasks/install_nodejs.yaml
    - name: Run neovim install tasks
      include_tasks: ../../tasks/install_neovim.yaml
