# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        exclude: ^(services|setup|docs)/
  - repo: https://github.com/pycqa/pylint
    rev: v2.10.2
    hooks:
      - id: pylint
        exclude: ^(services|setup|docs)/
        args:
          # - --max-line-length=80
          # - --ignore-patterns="^services/**/*.py"
          - --ignore-imports=yes
          - -d duplicate-code
  - repo: local
    hooks:
      # - id: isort
      #   name: isort
      #   stages: [commit]
      #   language: system
      #   entry: pipenv run isort
      #   types: [python]

      # - id: black
      #   name: black
      #   stages: [commit]
      #   language: system
      #   entry: pipenv run black
      #   types: [python]

      # - id: flake8
      #   name: flake8
      #   stages: [commit]
      #   language: system
      #   entry: pipenv run flake8 -v
      #   types: [python]
      #   exclude: setup.py,services/

      # - id: mypy
      #   name: mypy
      #   stages: [commit]
      #   language: system
      #   entry: pipenv run mypy
      #   types: [python]
      #   pass_filenames: false

      # - id: pytest
      #   name: pytest
      #   stages: [commit]
      #   language: system
      #   entry: pipenv run pytest -s
      #   types: [python]

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run pytest --cov --cov-fail-under=100
        types: [python]
        pass_filenames: false
