#!/bin/bash

# Copy thew current setting into the dotfile
# directory to save them

# cp -v dotfiles/.bash_profile ~/
cp -v ~/.vimrc dotfiles/vimrc 
cp -v ~/.tmux.conf dotfiles/tmux.conf
cp -v ~/.config/i3/ dotfiles/

# cp -v dotfiles/.gitconfig ~/
# cp -vr dotfiles/.vim ~/

# source ~/.bashrc
