#!/bin/bash

# Copy the setting form the dotfile 
# diroectory where they need to go

# cp -v dotfiles/.bash_profile ~/

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR="$DIR"

LOCAL_REPO="$DIR"
SOURCE_BASH="source $LOCAL_REPO/bash/bashrc"
SOURCE_VIM="source $LOCAL_REPO/vim/vimrc"
SOURCE_GIT="$LOCAL_REPO/git/gitconfig"

echo $DIR $LOCAL_REPO

# test bash rc
# grep -F fixed string -x exactly match the line -q do it quietly
if grep -Fxq "$SOURCE_BASH" ~/.bashrc
then
    echo "Bashrc Already modified"
else
    # Add bash scripts
    echo "" >> ~/.bashrc 
    echo $SOURCE_BASH >> ~/.bashrc 
    echo "Bashrc modified"
    # Source the main bash rc file
    echo "Reload .bashrc"
    source ~/.bashrc
fi

# Add vim init scripts
# cp -v $LOCAL_REPO/vim/vimrc ~/.vimrc
if [ ! -d ~/.config/nvim/ ]; then
    mkdir -p ~/.config/nvim/;
fi;
# Added file for neovim
echo "source ~/.vimrc" > ~/.config/nvim/init.vim
# Test and add vimrc file on home dir for both neovim (above) and vim
if grep -Fxq "$SOURCE_VIM" ~/.vimrc
then
    echo "Vimrc Already modified"
else
    # Add vim scripts
    # echo "" >> ~/.vimrc 
    echo $SOURCE_VIM > ~/.vimrc 
    echo "vimrc modified"
fi

# Add the config for Tmux
cp -v $LOCAL_REPO/tmux/tmux.conf ~/.tmux.conf

# Add .gitconfig

echo "[include]
    path = $SOURCE_GIT"  >> ~/.gitconfig

# cp -v dotfiles/.config ~/
# cp -v dotfiles/.gitconfig ~/

