#!/bin/bash

# Copy the setting form the dotfile 
# diroectory where they need to go

# cp -v dotfiles/.bash_profile ~/

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR="$DIR"

LOCAL_REPO="$DIR"
SOURCE_BASH_PATTERN="source $LOCAL_REPO/configs/bash/bashrc"
SOURCE_VIM_PATTERN="source $LOCAL_REPO/configs/vim/vimrc"
SOURCE_PATH_GIT="$LOCAL_REPO/configs/git/gitconfig"
SOURCE_PATH_TMUX="$LOCAL_REPO/configs/tmux/tmux.conf"
SOURCE_PATH_I3="$LOCAL_REPO/configs/i3/config"

CONFIG_PATH_BASH="$HOME/.bashrc"
CONFIG_PATH_VIM="$HOME/.vimrc"
CONFIG_PATH_NEOVIM="$HOME/.config/nvim/"
CONFIG_FILE_NEOVIM="$HOME/.config/nvim/vimrc"

echo $DIR $LOCAL_REPO

# test bash rc
# grep -F fixed string -x exactly match the line -q do it quietly
if grep -Fxq "$SOURCE_BASH_PATTERN" $CONFIG_PATH_BASH
then
    echo "Bashrc Already modified"
else
    # Add bash scripts
    echo "" >> $CONFIG_PATH_BASH
    echo $SOURCE_BASH_PATTERN >> $CONFIG_PATH_BASH
    echo "Bashrc modified"
    # Source the main bash rc file
    echo "Reload .bashrc"
    source $CONFIG_PATH_BASH
fi

# Add neovim init scripts
# cp -v $LOCAL_REPO/vim/vimrc ~/.vimrc
if [ ! -d $CONFIG_PATH_NEOVIM ]; then
    mkdir -p $CONFIG_PATH_NEOVIM;
fi;
# Added file for neovim
echo "source ~/.vimrc" > $CONFIG_FILE_NEOVIM

# Test and add vimrc file on home dir for both neovim (above) and vim
if grep -Fxq "$SOURCE_VIM_PATTERN" $CONFIG_PATH_VIM
then
    echo "Vimrc Already modified"
else
    # Add vim scripts
    # echo "" >> ~/.vimrc 
    echo $SOURCE_VIM_PATTERN > $CONFIG_PATH_VIM
    echo "vimrc modified"
fi

# Add the config for Tmux
cp -v $SOURCE_PATH_TMUX ~/.tmux.conf

# Add the config for i3
cp -v $SOURCE_PATH_I3 ~/.config/i3/config


# Add .gitconfig
echo "[include]
    path = $SOURCE_PATH_GIT"  >> ~/.gitconfig

# cp -v dotfiles/.config ~/
# cp -v dotfiles/.gitconfig ~/

