---
- name: Provision ubuntu server
  hosts: localhost
  # when: op == "create"
  tags: create
  vars_files:
    - terraform_vars.yml
    - terraform_auth.yml
  vars:
    state: testing
    group_to_build: proxmox
  tasks:
    - name: Provision debug
      debug:
        msg: |
          Provision

    # - name: run terraform
    #   include_tasks: terraform_server_proxmox.yml
    #   vars:
    #     state: "present"
    - name: Build machines using terraform
      include_tasks: terraform_tasks.yml
      vars:
        state: "present"
        vm: "{{
          hostvars[item].tf_openstack | combine(
            {
              'name': hostvars[item].ansible_host,
              'api_url': hostvars[item].tf_openstack_url,
            }
          )
          }}"
        tf_project_dir: "{{ tf_project_dir_template }}"
        # tf_project_dir: "{{ playbook_dir }}/project_{{ item }}"
        tf_auth: "{{ proxmox_auth }}"
      loop: "{{ groups[group_to_build] }}"
      register: tf_result
      loop_control:
        label: "Create {{ item }} on the proxmox server using terraform"

    - name: Show terraform result for creating machines
      debug:
        msg: |
          Result:
          {{ tf_result | to_nice_yaml }}
