---
# Further information https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
#
all:
  hosts:
    localhost:
      ansible_connection: local
    dev:
      awx_host_enable: no
      ansible_user: ubuntu
      ansible_host: dev.munnox.com
      # ansible_ssh_private_key_file: keyfilepath

disabled:
  hosts:
    # dev:
