---
# Further information https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
#
all:
  hosts:
    localhost:
      ansible_connection: local
      # ansible_user: ubuntu
      # ansible_host: example.com
      # ansible_ssh_private_key_file: keyfilepath
    testing:
      awx_host_enable: no
    rocky:
      awx_host_enable: no

disabled:
  hosts:
    # dev:
