# Start a simple jupyter lab
lab:
	docker-compose up -d
# Stop the lab
stop:
	docker-compose down
# Ask the container to set a password
pass:
	docker-compose exec lab jupyter notebook password
# Restart the container system
restart:
	docker-compose restart lab
