---
- name: config deploy
  hosts: localhost
  vars:
    nodejs_version: "v14.15.3"
    set_language: False
    install_neovim: False
    install_nodejs: False
    name: Robert Munnoch
    email: robert@munnox.com
  tasks:
    # - name: Ping the machine to deploy
    #   ping:
    # - name: Print the playbook dir
    #   ansible.builtin.debug:
    #     var: playbook_dir
    - name: Compute the repo config dir
      set_fact:
        repo_config_path: "{{ (playbook_dir, '../configs') | path_join | realpath }}"
    # - name: Print the repo config dir
    #   ansible.builtin.debug:
    #     var: repo_config_path

    - name: Detect distro
      include_tasks: "{{ (playbook_dir, 'tasks/detect_distro.yaml') | path_join | realpath }}"

    - name: summary
      ansible.builtin.debug:
        msg: |
          {{ debian_family }}
          {{ rhel_family }}
          {{ systemd_present }}

    - name: Uncomment the en_GB language for localegen but if not don't panic
      # become: yes
      include_tasks: "{{ (playbook_dir, 'tasks/set_gb_lang.yaml') | path_join | realpath }}"
      when: set_language

    # Install Neovim Appimage
    - name: Run neovim install tasks
      include_tasks: "{{ (playbook_dir, 'tasks/install_neovim.yaml') | path_join | realpath }}"
      when: install_neovim
      tags: install_neovim


    # Install NodeJS
    - name: Run nodejs install tasks
      include_tasks: "{{ (playbook_dir, 'tasks/install_nodejs.yaml') | path_join | realpath }}"
      when: install_nodejs
      tags: install_nodejs

    # Setup Bash
    - name: test bash
      command: which bash
      register: result
      ignore_errors: yes
      changed_when: false
    - name: Is bash present
      ansible.builtin.set_fact:
        bash_present: "{{ result.rc == 0 }}"
    - name: Add config set redirect bashrc
      blockinfile:
        path: "{{ '~/.bashrc' | expanduser }}"
        marker: "# {mark} ANSIBLE MANAGED UNIX_CONFIG BLOCK"
        # insertafter: "<body>"
        block: |
          source {{repo_config_path}}/bash/bashrc
        create: yes
      when: bash_present

    # Setup GIT
    - name: test git
      command: which git
      register: result
      ignore_errors: yes
      changed_when: false
    - name: Is git present
      ansible.builtin.set_fact:
        git_present: "{{ result.rc == 0 }}"
    - name: Add config set redirect gitconfig
      blockinfile:
        path: "{{ '~/.gitconfig' | expanduser }}"
        marker: "# {mark} ANSIBLE MANAGED UNIX_CONFIG BLOCK"
        # insertafter: "<body>"
        block: |
          [include]
              path = {{repo_config_path}}/git/gitconfig
          [user]
              name = {{name}}
              email = {{email}}
        create: yes
      when: git_present

    # Setup I3 symlink
    - name: test I3
      command: which i3
      register: result
      ignore_errors: yes
      changed_when: false
    - name: Is I3 present
      ansible.builtin.set_fact:
        i3_present: "{{ result.rc == 0 }}"
    - name: Create a symbolic link I3 config
      ansible.builtin.file:
        src: "{{repo_config_path}}/i3/config"
        dest: "{{ '~/.config/i3/config' | expanduser }}"
        # owner: foo
        # group: foo
        state: link
      when: i3_present
    - name: Create a symbolic link I3status config
      ansible.builtin.file:
        src: "{{repo_config_path}}/i3/i3status.conf"
        dest: "{{ '~/.config/i3status/config' | expanduser }}"
        # owner: foo
        # group: foo
        state: link
      when: i3_present

    # Setup Tmux symlink
    - name: test tmux
      command: which tmux
      register: result
      ignore_errors: yes
      changed_when: false
    - name: Is tmux present
      ansible.builtin.set_fact:
        tmux_present: "{{ result.rc == 0 }}"
    - name: Create a symbolic link tmux config
      ansible.builtin.file:
        src: "{{repo_config_path}}/tmux/tmux.conf"
        dest: "{{ '~/.tmux.conf' | expanduser }}"
        # owner: foo
        # group: foo
        state: link
      when: tmux_present

    # Setup alacritty symlink
    # - name: test alacritty
    #   command: which alacritty
    #   register: result
    #   ignore_errors: yes
    #   changed_when: false
    - name: Is alacritty present force yes
      ansible.builtin.set_fact:
        # alacritty_present: "{{ result.rc == 0 }}"
        alacritty_present: yes
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ '~/.config/alacritty/' | expanduser }}"
        state: directory
        mode: '0755'
      when: alacritty_present
    - name: Create a symbolic link alacritty config
      ansible.builtin.file:
        src: "{{repo_config_path}}/alacritty/alacritty.yml"
        dest: "{{ '~/.config/alacritty/alacritty.yml' | expanduser }}"
        # owner: foo
        # group: foo
        state: link
      when: alacritty_present

    # Setup helix copy
    # - name: test Helix
    #   command: which hx
    #   register: result
    #   ignore_errors: yes
    #   changed_when: false
    - name: Is Helix present forced yes
      ansible.builtin.set_fact:
        # helix_present: "{{ result.rc == 0 }}"
        helix_present: yes
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ '~/.config/helix/' | expanduser }}"
        state: directory
        mode: '0755'
      when: helix_present
    - name: Create a symbolic link helix config
      ansible.builtin.copy:
        src: "{{repo_config_path}}/helix/config.toml"
        dest: "{{ '~/.config/helix/config.toml' | expanduser }}"
        # # owner: foo
        # # group: foo
        # state: link
      when: helix_present

    # Setup zsh
    - name: test zsh
      command: which zsh
      register: result
      ignore_errors: yes
      changed_when: false
    - name: Is zsh present
      ansible.builtin.set_fact:
        zsh_present: "{{ result.rc == 0 }}"
    - name: Add config set redirect zsh
      blockinfile:
        path: "{{ '~/.zshrc' | expanduser }}"
        marker: "# {mark} ANSIBLE MANAGED UNIX_CONFIG BLOCK"
        # insertafter: "<body>"
        create: yes
        block: |
          source {{repo_config_path}}/zsh/zshrc
      when: zsh_present

    # Setup vim
    - name: test vim
      command: which vim
      register: result
      ignore_errors: yes
      changed_when: false
    - name: Is neovim present
      ansible.builtin.set_fact:
        vim_present: "{{ result.rc == 0 }}"
    - name: Add config set redirect neovim
      blockinfile:
        path: "{{ '~/.vimrc' | expanduser }}"
        marker: "\" {mark} ANSIBLE MANAGED UNIX_CONFIG BLOCK"
        # insertafter: "<body>"
        block: |
          source {{repo_config_path}}/vim/vimrc
        create: yes
      when: vim_present

    # Setup neovim
    - name: test neovim
      command: which nvim
      register: result
      ignore_errors: yes
      changed_when: false
    - name: Is neovim present
      ansible.builtin.set_fact:
        neovim_present: "{{ result.rc == 0 }}"
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ '~/.config/nvim/' | expanduser }}"
        state: directory
        mode: '0755'
      when: neovim_present
    - name: Add config set redirect neovim
      blockinfile:
        path: "{{ '~/.config/nvim/init.vim' | expanduser }}"
        marker: "\" {mark} ANSIBLE MANAGED UNIX_CONFIG BLOCK"
        # insertafter: "<body>"
        block: |
          source {{ '~/.vimrc' | expanduser }}
        create: yes
      when: neovim_present

    - name: Report
      debug:
        msg: |
          install nodejs: {{install_nodejs}}
          install neovim: {{install_neovim}}
          install neovim as appimage: {{neovim.install_appimage | default('no neovim')}}
          vim present?: {{vim_present}}
          git present?: {{git_present}}
          neovim present?: {{neovim_present}}
          i3 present?: {{i3_present}}
          tmux present?: {{tmux_present}}
          bash present?: {{bash_present}}
          alacritty present?: {{alacritty_present}}
          helix present?: {{helix_present}}
          zsh present?: {{zsh_present}}
