---

- name: config deploy
  hosts: localhost
  tasks:
    - name: testing
      ping:
    - name: debug hostvars
      ansible.builtin.debug:
        var: inventory_hostname
    - name: debug hostvars
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]

