- name: Create VM on KVM hypervisior
  hosts: "{{ playbook_groups | default('kvm_hosts') }},!disabled"
  vars:
    ssh_pub_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_ed25519.pub') }}"
    machines: "{{
        vm_guests
        | default([])
        | munnox.bootstrap.vm_guest_definition(
            hostvars,
            connection=virt_vm_connection | default('bridge=default'),
            ssh_key_pub=ssh_key_pub
          )
      }}"
    # machines: "{{ vm_guests }}"

    # Inital virtual guests from the desk-rob vm_guests variable
    virtual_guests: "{{ vm_guests | default([]) }}"

  tasks:
    - name: Manage virtual machines on kvm hypervisor
      ansible.builtin.import_role:
        name: munnox.bootstrap.libvirt
        tasks_from: main.yml
