- name: Create VM on KVM hypervisior
  # hosts: "{{ playbook_groups | default('kvm_hosts') }},!disabled"
  hosts: "desk-rob"
  vars:
    ssh_pub_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_ed25519.pub') }}"
    machines: "{{ vm_guests }}"

  tasks:
    - name: Update package manager
      ansible.builtin.import_role:
        name: munnox.bootstrap.libvirt
        tasks_from: kvm_create_machine.yml
