#!/bin/bash

# export LC_ALL=C.UTF-8
# export LANG=C.UTF-8
# export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8
export TZ=Europe/London

# unset RAM_ORG_PATH
export RAM_ORG_PATH=${RAM_ORG_PATH:-$PATH}

# Array of localscripts
LOCALSCRIPTS=(
../bash/bash_alias.sh
../bash/bash_display.sh
../bash/bash_terminal.sh
../bash/bash_env.sh
../bash/bash_prompt.sh
../bash/bash_lscolours.sh
../bash/bash_setup.sh
../bash/bash_kubernetes.sh
../bash/bash_tmux.sh
../bash/bash_terminal.sh
)

# Gets the current path of this source file
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR="$DIR"

export PATH="./:$RAM_ORG_PATH"

# Source all file defined above
for p in ${LOCALSCRIPTS[@]}; do
    if [ -s "$DIR/$p" ]; then
        # echo "sourcing --> $p"
        source "$DIR/$p"
    else
        echo "Error: $DIR/$p cannot be found"
    fi
done

# If the cargo directry exists source it
# This loads cargo for a rust environment
[ -s "~/.cargo/env" ] && \. "~/.cargo/env"

# Node NVM setup and config first checking if the directory exists
export NVM_DIR="$HOME/.ramnvm"
# This loads nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# This loads nvm bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# # git branch autocompletion
# if [ -f ~/dotfiles/.git-completion.bash ]; then
#   . ~/dotfiles/.git-completion.bash
# fi

# disable the ctrl-s
stty -ixon
