#!/bin/bash

# Gets the current path of this source file
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR="$DIR"

# Array of localscripts
LOCALSCRIPTS=(
../bash/bash_alias.sh 
../bash/bash_display.sh
../bash/bash_terminal.sh
../bash/bash_env.sh
../bash/bash_prompt.sh
../bash/bash_lscolours.sh
)

for p in ${LOCALSCRIPTS[@]}; do
    # echo "sourcing --> $p"
    source "$DIR/$p"
done

# If the cargo directry exists source it
[ -s "~/.cargo/env" ] && \. "~/.cargo/env"  # This loads cargo for rust

# NVM setup and config
export NVM_DIR="$HOME/.ramnvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# # git branch autocompletion
# if [ -f ~/dotfiles/.git-completion.bash ]; then
#   . ~/dotfiles/.git-completion.bash
# fi

# disable the ctrl-s
# stty -ixon

