---
- name: Install an NFS mount
  hosts: "{{ playbook_groups | default('nfs') }},!disabled"

  vars:
    # nfs_server: 192.168.0.1
    # nfs_share_uri: /vol/share
    # nfs_share_path: /mnt/share
    # # nfs_state: present
    # nfs_state: absent

    nfs_server: 192.168.0.1
    nfs_share_uri: /export/test
    nfs_share_path: /mnt/test
    nfs_state: present
    username: auser
    # nfs_state: absent
  tasks:
    - name: install nfs packages
      become: yes
      block:
        - name: Install nfs on Redhat, CentOS or Rocky
          ansible.builtin.package:
            name: nfs-utils
            state: present
          when: ansible_os_family == 'RedHat'
        - name: Install NFS on Debian and ubuntu
          ansible.builtin.package:
            name: nfs-common
            state: present
          when: ansible_os_family == 'Debian'
      when: nfs_state == 'present'
    - name: Remove in case mount to fstab
      become: yes
      ansible.posix.mount:
        src: "{{ nfs_server }}:{{ nfs_share_uri }}"
        path: "{{ nfs_share_path }}"
        fstype: nfs
        state: absent
        # opts: rw,sync,hard,intr
    - name: Make a directory for the share
      become: yes
      ansible.builtin.file:
        path: "{{ nfs_share_path }}"
        state: directory
        mode: '0775'
        owner: "{{ username }}"
        group: "{{ username }}"
      when: nfs_state == 'present'

    # - name: Add mount to fstab
    #   become: yes
    #   ansible.builtin.lineinfile:
    #     path: /etc/fstab
    #     line: {{ nfs_server }}:{{ nfs_share_uri }} {{ nfs_share_path }} nfs auto 0 0
    - name: Add the mount to fstab
      become: yes
      ansible.posix.mount:
        src: "{{ nfs_server }}:{{ nfs_share_uri }}"
        path: "{{ nfs_share_path }}"
        fstype: nfs
        state: mounted
        opts: rw,sync  
        #,hard,intr
      when: nfs_state == 'present'

    # - name: ensure permissions
    #   become: yes
    #   ansible.builtin.file:
    #     path: "{{ nfs_share_path }}"
    #     state: directory
    #     mode: '0777'
    #     owner: "{{ username }}"
    #     group: "{{ username }}"
    #   when: nfs_state == 'present'
    
    - name: clear a dir
      become: yes
      ansible.builtin.file:
        path: "{{ nfs_share_path }}"
        state: absent
      when: nfs_state == 'absent'
