- name: Ping hosts and display info summary for playbook_group={{ playbook_group | default('localhost') }}
  hosts: "{{ playbook_groups | default('localhost') }},!disabled"
  tasks:
    - name: Ping hosts
      ansible.builtin.ping: