---
# Need dependancies
# ansible-galaxy collection install azure.azcollection
# pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt~/.ansible/roles/azure.azure_modules/files/requirements-azure.txt
- name: Make Vm on Azure
  hosts: all
  gather_facts: yes
  vars:
    ssh_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCchNdQAz0Tn2xfzAQKzptSlFpAd1mYAL9t58cQUryv4ALYF80BBKg2hqzYY/W3quhp7MZeWPm4Prf1Rnfk2s1gW67sHHt4cnV29QVO10S0pRlZpVTkDIdXAq3PVY0nzSH5RGXzHRECcBsThKCEbUvUVOZVd1qV81kWPNH2reN18p82+YcqtQncYl0pPEOWxA1aB4nLU36tzjgTibA2axvsWrnf0yK/ln2SpyhXVyaxhXJEPjMsdhmj9XeyRj/Pg3AMEB0X5ChrziE95m9Ogkkb1eeIYyJsHXn8l/wPgDgSjq4qu0xC8V+QboQfyCkGmzwjeterdqLutkJ232PFsD9a+jb95AP25haW1b6V2/6nKYPdY3+LymKzs+paJBKtafuEP41RaQ55WkYuyI8To4XfV/4pzQMZ7q5RMemLkbakTAFONqvx926+DyfnOGfbuJHZaZLUrUUm367Z3z5Zo7xmfXgJazjVn4jDbt4ggbEwFzKSskO85BL0lHFV9R0UNbE= robert@sia"
    # This must be set as the azure dependances need to be found
    # ansible_python_interpreter: "/home/robert/.local/share/virtualenvs/deploy-eGhfOb-l/bin/python"
    ansible_python_interpreter: "{{lookup('env', 'VIRTUAL_ENV')}}/bin/python"
    vm:
      name: instance
      resource_group: rg_instance
      location: uksouth
  tasks:
    - name: Create Resource group
      shell: |
        echo "Hello world"
    - name: smmary
      ansible.builtin.debug:
        msg: |
          {{ansible_facts}}
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ vm.resource_group }}"
        location: "{{ vm.location }}"
        tags:
            testing: testing
    - name: List all available images under current subscription
      azure_rm_image_info:

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{vm.resource_group}}"
        name: "{{vm.name}}_Vnet"
        address_prefixes: "10.0.0.0/16"
    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{vm.resource_group}}"
        name: "{{vm.name}}_Subnet"
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{vm.name}}_Vnet"
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{vm.resource_group}}"
        allocation_method: Static
        name: "{{vm.name}}_PublicIP"
      register: output_ip_address
    - name: Public IP of VM
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}."
    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{vm.resource_group}}"
        name: "{{vm.name}}_NetworkSecurityGroup"
        rules:
          - name: SSH
            protocol: Tcp
            # source_address_prefix: "*"
            source_address_prefix: "82.33.88.95/32"
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: GITEA
            protocol: Tcp
            # source_address_prefix: "*"
            source_address_prefix: "82.33.88.95/32"
            destination_port_range: 3000-3001
            access: Allow
            priority: 1002
            direction: Inbound
    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{vm.resource_group}}"
        name: "{{vm.name}}_NIC"
        virtual_network: "{{vm.name}}_Vnet"
        subnet: "{{vm.name}}_Subnet"
        public_ip_name: "{{vm.name}}_PublicIP"
        security_group: "{{vm.name}}_NetworkSecurityGroup"
    - name: create an account
      azure_rm_storageaccount:
        resource_group: "{{vm.resource_group}}"
        name: "{{vm.name}}drivesgrp"
        type: Standard_RAGRS
        tags:
          testing: testing
          delete: on-exit
    - name: Create virtual machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{vm.resource_group}}"
        name: "{{vm.name}}"
        location: "{{vm.location}}"
        # Standard_B2ms 2vcpu 8GB costs £55.50 per month 0.0760 £/hr for windows 2019
        vm_size: Standard_B2ms
        storage_account: "{{vm.name}}drivesgrp"
        storage_container: "{{ vm.name }}"
        storage_blob: "{{ vm.name }}.vhd"
        admin_username: ansible
        # admin_password: Password!
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/ansible/.ssh/authorized_keys" 
            key_data: "{{ ssh_keys }}"
        
        network_interfaces: "{{vm.name}}_NIC"
        image:
          offer: 0001-com-ubuntu-server-focal
          publisher: Canonical
          sku: '20_04-lts'
          version: latest
    
  