# Create a new instance in Openstack 
# automatically assigns a floating IP

# Create instance
# ansible-playbook playbooks/clouds/openstack/manage_instances.yml
# Destroy instance
# ansible-playbook playbooks/clouds/openstack/manage_instances.yml \
#   --extra-vars "{destroy_instances: [{name: openstack_test_default, state: absent}]}"
- name: launch a compute instance
  hosts: localhost
  # vars:
  #   ansible_python_interpreter: /home/robert/.cache/pypoetry/virtualenvs/home-5Vd7lvN--py3.9/bin/python
  vars_files:
    # Auth in yaml file in the style of cloud.yaml
    # https://docs.openstack.org/python-openstackclient/pike/configuration/index.html
    - "../../../credentials/clouds.yml"
  vars:
    flavors:
      cheap: d2-2
      # Rough list of costs
      # d2-2 - 2 Core 2GB 25GB - £0.00818 per hour £4.53 Month
      # d2-4 - 2 Core 4GB 50GB - £0.01636 per hour £9.06 Month flavor: 4d4fd037-9493-4f2b-9afe-b542b5248eac
      # d2-8 - 2 Core 8GB 50GB - £0.02947 per hour £16.32 Month
      # b2-7 - 2 Core 7GB 50GB - £0.0589 per hour £21.09 Month
      # b2-15 - 4 Core 15GB 100GB - £0.1119 per hour £40.19 Month
      # b2-30 - 8 Core 30GB 200GB - £0.2259 per hour £81.19 Month
      # b2-60 - 16 Core 60GB 400GB - £0.4379 per hour £157.59 Month
    template:
      # Rocky Linux 8 - image: 9e3dd45d-b95e-49b0-938d-7440badaa0b8
      rocky:
        image: "Rocky Linux 8" 
        user: rocky
      # Ubuntu 20.04 - image: 35564baf-593c-431f-b4ae-25f0f8810ea5
      ubuntu:
        image: "Ubuntu 20.04"
        user: ubuntu
      alma:
        image: "AlmaLinux 8"
        user: almalinux
    # Simple example instance to create
    create_instances: 
    - name: 'openstack_test_default'
      state: 'present'
      image: 'Rocky Linux 8'
      flavor: 'd2-2'
      tags:
        role: testing
        user: rocky
      key_name: "{{ keys_name }}"
      security_groups:
      - "default"
    # Simple example instance template to destory
    # Just rename this
    destroy_instances_template: 
    - name: 'openstack_test_default'
      state: 'absent'
    # This now has a switch to use a different variable is provided
    # So by default it will create a VM but if given a
    # destroy_instances variable it can change behaviour
    # Comment or uncomment this line to remove test vm
    # destroy_instances: "{{ destroy_instances_template }}"
    instances: "{{ destroy_instances | default(create_instances) }}"
  tasks:
  - name: Print instances
    debug:
      msg: |
        {{ instances | to_yaml }}

  - name: Launch or Update instances
    loop: "{{ instances }}"
    loop_control:
      label: "Start/Update state: {{server.state}} an instance called: {{ server.name }} with tags: {{ item.tags | default({}) }}"
      loop_var: server
    when: server.state != 'absent'
    openstack.cloud.server:
      auth:
        auth_url: "{{ openstack_auth.auth_url }}"
        username: "{{ openstack_auth.username }}"
        password: "{{ openstack_auth.password }}"
        project_name: "{{ openstack_auth.project_name }}"
        domain_name: "{{ openstack_auth.domain_name }}"
        project_domain_name: "{{ openstack_auth.project_domain_name }}"
      state: "{{ server.state }}"
      name: "{{ server.name }}"
      region_name: "{{ server.region | default('UK1') }}"
      # availability_zone: UK1
      image: "{{ server.image }}"
      key_name: "{{ server.key_name }}"
      # timeout: 200
      flavor: "{{ server.flavor }}"
      security_groups: "{{ server.security_groups | default('default') }}"
      # auto_ip: yes
      meta: "{{ server.tags }}"
    register: server_creation

  - name: Remove instances
    loop: "{{ instances | default([
        {
          'name': 'openstack_test_default',
          'state': 'absent'
        }
      ])}}"
    loop_control:
      label: "Stop state: {{server.state}} an instance called: {{ server.name }}"
      loop_var: server
    when: server.state == 'absent'
    openstack.cloud.server:
      auth:
        auth_url: "{{ clouds.os.auth.auth_url }}"
        username: "{{ clouds.os.auth.username }}"
        password: "{{ clouds.os.auth.password }}"
        project_name: "{{ clouds.os.auth.project_name }}"
        domain_name: "{{ clouds.os.auth.domain_name }}"
        project_domain_name: "{{ clouds.os.auth.project_domain_name }}"
      state: "{{ server.state }}"
      name: "{{ server.name }}"
    register: server_removal
    
  # - name: debug results
  #   debug:
  #     msg: |
  #       Creation:
  #       {{ server_creation | default('skipped') | to_yaml }}
  #       Removal:
  #       {{ server_removal | default('skipped') | to_yaml }}

  - name: add ssh config block
    ansible.builtin.blockinfile:
      path: "~/.ssh/config"
      # path: "./config"
      block: |
        host {{ item.server.name }}
          hostname {{ item.openstack.accessIPv4 }}
          user {{ item.openstack.metadata.user }}
          stricthostkeychecking no
          userknownhostsfile=/dev/null
      marker: "# {mark} ansible managed block for openstack {{ item.server.name }}"
      create: yes
    delegate_to: localhost
    when: item.server.state == "present"
    loop: "{{ server_creation.results }}"
    no_log: yes

  - name: remove ssh config block
    ansible.builtin.blockinfile:
      path: "~/.ssh/config"
      marker: "# {mark} ansible managed block for openstack {{ item.server.name }}"
    when: item.server.state == "absent" and item.result == 'deleted'
    loop: "{{ server_removal.results }}"
    delegate_to: localhost
    no_log: yes

  - name: Wait 10 seconds then check for port 22 to become open for all the servers
    wait_for:
      host: "{{ item.openstack.accessIPv4 }}" 
      port: 22
      delay: 5
      sleep: 2
      timeout: 300
    when: item.server.state == "present"
    loop: "{{ server_creation.results }}"
    no_log: yes
    