---
- name: config deploy
  hosts: localhost
  vars:
    # nodejs_version: "v14.17.5"
    # nodejs_install: False
    nodejs:
      install_flag: no
  tasks:
    - name: Run nodejs install tasks
      include_tasks: ../tasks/install_nodejs.yaml
    - name: please fail
      fail:
