- name: encrypt all credential files
  hosts: localhost
  vars:
    base_dir: "{{ (playbook_dir, '..') | path_join | realpath }}"
    filemapping:
    - file: "{{ (base_dir, 'credentials/clouds.yml') | path_join }}"
      key:  "{{ (base_dir, 'vault_password_cloud') | path_join }}"
      id: cloud
  tasks:
  - name: Encrypt the vault items {{ base_dir }}
    tags:
      - encrypt
    loop: "{{ filemapping }}"
    loop_control:
      label: Encypting {{ item.file }} using the {{ item.key }} Key file
    shell: |
      ansible-vault encrypt --vault-id {{item.id}}@{{ item.key }} {{ item.file }}
    register: enc
    failed_when: "enc.stderr != '' and 'ERROR! input is already encrypted' not in enc.stderr"
    # changed_when: no
    changed_when: "enc.stderr == '' and enc.stdout == ''"
    
  - name: Decrypt the vault items
    tags:
      - decrypt
    loop: "{{ filemapping }}"
    loop_control:
      label: Decypting {{ item.file }} using the {{ item.key }} Key file
    shell: |
      ansible-vault decrypt --vault-id {{item.id}}@{{ item.key }} {{ item.file }}
    register: enc
    failed_when: "enc.stderr != '' and 'ERROR! input is not vault encrypted data.' not in enc.stderr"
    changed_when: "enc.stderr == '' and enc.stdout == ''"
